notes/urls.py
from django.urls import path

from notes import views

app_name = 'notes'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add/', views.NoteCreate.as_view(), name='add'),
    path('edit/<slug:slug>/', views.NoteUpdate.as_view(), name='edit'),
    path('note/<slug:slug>/', views.NoteDetail.as_view(), name='detail'),
    path('delete/<slug:slug>/', views.NoteDelete.as_view(), name='delete'),
    path('notes/', views.NotesList.as_view(), name='list'),
    path('done/', views.NoteSuccess.as_view(), name='success'),
]

triplenote/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path
from django.views.generic import CreateView

urlpatterns = [
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
]

auth_urls = ([
    path(
        'login/',
        auth_views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='registration/logout.html'
        ),
        name='logout',
    ),
    path(
        'signup/',
        CreateView.as_view(
            form_class=UserCreationForm,
            success_url='/',
            template_name='registration/signup.html',
        ),
        name='signup'
    ),
], 'users')

urlpatterns += [path('auth/', include(auth_urls))]

notes/models.py
from django.conf import settings
from django.db import models

from pytils.translit import slugify


class Note(models.Model):
    title = models.CharField(
        'Title',
        max_length=100,
        default='Title of note',
        help_text='Give a short title to the note'
    )
    text = models.TextField(
        'Body',
        help_text='Add more details'
    )
    slug = models.SlugField(
        'Address for the page with a note',
        max_length=100,
        unique=True,
        blank=True,
        help_text=('Indicate the address for the note page. Use only '
                   'Latin characters, numbers, hyphens and underscores')
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_slug_by_title(self.title)
        super().save(*args, **kwargs)

    @classmethod
    def get_slug_by_title(cls, title):
        """Creating a slug for a note based on the title."""
        max_slug_length = cls._meta.get_field('slug').max_length
        return slugify(title)[:max_slug_length]

notes/forms.py
from pytils.translit import slugify

from django import forms
from django.core.exceptions import ValidationError

from .models import Note

WARNING = ' - such a slug already exists; come up with a unique value!'


class NoteForm(forms.ModelForm):
    """Form for creating or updating a note."""

    class Meta:
        model = Note
        fields = ('title', 'text', 'slug')

    def clean_slug(self):
        """Processes the cases where slug is not unique."""
        cleaned_data = super().clean()
        slug = cleaned_data.get('slug')
        if not slug:
            title = cleaned_data.get('title')
            slug = Note.get_slug_by_title(title)
        if Note.objects.filter(
                slug=slug
        ).exclude(id=self.instance.pk).exists():
            raise ValidationError(slug + WARNING)
        return slug

notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from .forms import NoteForm
from .models import Note


class Home(generic.TemplateView):
    """Homepage."""
    template_name = 'notes/home.html'


class NoteSuccess(LoginRequiredMixin, generic.TemplateView):
    """Success page for completed operation."""
    template_name = 'notes/success.html'


class NoteBase(LoginRequiredMixin):
    """Base class for the rest of the CBVs."""
    model = Note
    success_url = reverse_lazy('notes:success')

    def get_queryset(self):
        """The user can only work with their own notes."""
        return self.model.objects.filter(author=self.request.user)


class NoteCreate(NoteBase, generic.CreateView):
    """Adding a note."""
    template_name = 'notes/form.html'
    form_class = NoteForm

    def form_valid(self, form):
        new_note = form.save(commit=False)
        new_note.author = self.request.user
        new_note.save()
        return super().form_valid(form)


class NoteUpdate(NoteBase, generic.UpdateView):
    """Editing a note."""
    template_name = 'notes/form.html'
    form_class = NoteForm


class NoteDelete(NoteBase, generic.DeleteView):
    """Deleting a note."""
    template_name = 'notes/delete.html'


class NotesList(NoteBase, generic.ListView):
    """List of all user's notes."""
    template_name = 'notes/list.html'


class NoteDetail(NoteBase, generic.DetailView):
    """The note is detailed."""
    template_name = 'notes/detail.html'

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous">
  </head>
  <body class="bg-light">
    {% include "includes/header.html" %}
    <div class="container mt-3">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/includes/errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'notes:home' %}">
        <span class="text-danger"><b>Triple</b></span>Note
      </a>
      {% if user.is_authenticated %}
          <div class="nav-item align-self-center mt-1">
            user {{ user.username }}
          </div>
        <div class="spacer flex-grow-1"></div>
      {% endif %}
      <ul class="nav nav-pills">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notes:list' %}">List of notes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notes:add' %}">New note</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">Sign up</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>

templates/notes/delete.html
{% extends "base.html" %}
{% block content %}
  <h2>Delete note {{ note.id }}?</h2>
  <hr>
  <h3>{{ note.title }}</h3>
  <p>{{ note.text }}</p>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" >Delete</button>
    </div>
  </form>
{% endblock content %}

templates/notes/detail.html
{% extends "base.html" %}
{% block content %}
  <h2>Note ID: {{ note.id }}</h2>
  <hr>
  <h3>{{ note.title }}</h3>
  <p>{{ note.text }}</p>
  <hr>
  <p>
    <a href="{% url 'notes:edit' slug=note.slug %}">Edit</a>
  </p>
  <p>
    <a href="{% url 'notes:delete' slug=note.slug %}">Delete</a>
  </p>
{% endblock content %}

templates/notes/form.html
{% extends "base.html" %}
{% block content %}
  <h2>
    {% if request.path == '/add/' %}
      Add
    {% else %}
      Edit
    {% endif %}
    note
  </h2>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {% include "includes/errors.html" %}
    <fieldset>
      <legend>{{ title }}</legend>
      {% for field in form %}
        <div class="control-group">
          <label class="control-label">{{ field.label }}</label>
          <div class="controls">
            {{ field }}
            {% if field.help_text %}
              <p class="help-inline"><small>{{ field.help_text }}</small></p>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    </fieldset>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" >Save</button>
    </div>
  </form>
{% endblock %}

templates/notes/home.html
{% extends "base.html" %}
{% block content %}
  <h2>About the project</h2>
  <p>
    The TripleNote project will help you to not forget the most important things!
  </p>
{% endblock content %}

templates/notes/list.html
{% extends "base.html" %}
{% block content %}
  <h2>List of notes</h2>
  <ul>
    {% for note in object_list %}
      <li>
        {{ note.id }}:
        <a href="{% url 'notes:detail' note.slug %}"> {{ note.title }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

templates/notes/success.html
{% extends "base.html" %}
{% block content %}
  <h2>Successful</h2>
  <ul>
    <li>
      <a href="{% url 'notes:home' %}">Back to main page</a>
    </li>
    <li>
      <a href="{% url 'notes:list' %}">To the list of notes</a>
    </li>
  </ul>
{% endblock content %}